// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionTracker.Infrastructure.Persistence;

#nullable disable

namespace NutritionTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    [Migration("20260723161419_AddChatConfirmationHash")]
    partial class AddChatConfirmationHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("NutritionTracker.Domain.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Chat.UserMessageProcessing", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClarificationResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InterpretationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingQuestion")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResponseDeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetryFromState")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolArgumentsHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolArgumentsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("UserId", "DeliveryKey")
                        .IsUnique();

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.ToTable("UserMessageProcessings", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserMessageProcessings_CompletedHasResult", "\"State\" <> 'Completed' OR \"ExecutionResultJson\" IS NOT NULL");

                            t.HasCheckConstraint("CK_UserMessageProcessings_OperationHasTool", "\"State\" NOT IN ('AwaitingConfirmation', 'Executing') OR (\"ToolName\" IS NOT NULL AND \"ToolArgumentsJson\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NutritionTracker.Domain.Commands.ProcessedCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ResultDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResultEntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ProcessedCommands", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Commands.ToolExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgumentsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ToolExecutions", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FiberPer100g")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("UserId");

                    b.ToTable("FoodProducts", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("Meals", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FoodProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MealId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecipeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodProductId");

                    b.HasIndex("MealId");

                    b.HasIndex("SourceMessageId");

                    b.HasIndex("RecipeId", "RecipeVersion");

                    b.ToTable("MealItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_MealItems_ExactlyOneSource", "(\"FoodProductId\" IS NOT NULL AND \"RecipeId\" IS NULL) OR (\"FoodProductId\" IS NULL AND \"RecipeId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NutritionTracker.Domain.Nutrition.NutritionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionTargets", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchiveSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalPreparedWeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "NormalizedName");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FoodProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.RecipeVersion", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalPreparedWeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId", "Version");

                    b.ToTable("RecipeVersions", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.RecipeVersionIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FoodProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId", "RecipeVersion", "FoodProductId");

                    b.HasIndex("FoodProductId");

                    b.ToTable("RecipeVersionIngredients", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Chat.ChatMessage", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Chat.UserMessageProcessing", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Chat.ChatMessage", null)
                        .WithOne()
                        .HasForeignKey("NutritionTracker.Domain.Chat.UserMessageProcessing", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Commands.ProcessedCommand", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Commands.ToolExecution", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodProduct", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("NutritionTracker.Domain.Nutrition.NutritionValues", "NutritionPer100g", b1 =>
                        {
                            b1.Property<Guid>("FoodProductId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CaloriesPer100g");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CarbohydratesPer100g");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("FatPer100g");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProteinPer100g");

                            b1.HasKey("FoodProductId");

                            b1.ToTable("FoodProducts");

                            b1.WithOwner()
                                .HasForeignKey("FoodProductId");
                        });

                    b.Navigation("NutritionPer100g")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.Meal", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.MealItem", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.FoodProduct", null)
                        .WithMany()
                        .HasForeignKey("FoodProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NutritionTracker.Domain.Meals.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Domain.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NutritionTracker.Domain.Chat.ChatMessage", null)
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NutritionTracker.Domain.Recipes.RecipeVersion", null)
                        .WithMany()
                        .HasForeignKey("RecipeId", "RecipeVersion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("NutritionTracker.Domain.Nutrition.NutritionValues", "NutritionSnapshot", b1 =>
                        {
                            b1.Property<Guid>("MealItemId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CaloriesSnapshot");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CarbohydratesSnapshot");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("FatSnapshot");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProteinSnapshot");

                            b1.HasKey("MealItemId");

                            b1.ToTable("MealItems");

                            b1.WithOwner()
                                .HasForeignKey("MealItemId");
                        });

                    b.Navigation("NutritionSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Nutrition.NutritionTarget", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("NutritionTracker.Domain.Nutrition.NutritionValues", "NutritionValues", b1 =>
                        {
                            b1.Property<Guid>("NutritionTargetId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("Calories");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CarbohydrateGrams");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("FatGrams");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProteinGrams");

                            b1.HasKey("NutritionTargetId");

                            b1.ToTable("NutritionTargets");

                            b1.WithOwner()
                                .HasForeignKey("NutritionTargetId");
                        });

                    b.Navigation("NutritionValues")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.Recipe", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.FoodProduct", null)
                        .WithMany()
                        .HasForeignKey("FoodProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Domain.Recipes.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.RecipeVersion", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Recipes.Recipe", null)
                        .WithMany("Versions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.RecipeVersionIngredient", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.FoodProduct", null)
                        .WithMany()
                        .HasForeignKey("FoodProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Domain.Recipes.RecipeVersion", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId", "RecipeVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NutritionTracker.Domain.Nutrition.NutritionValues", "NutritionPer100gSnapshot", b1 =>
                        {
                            b1.Property<Guid>("RecipeVersionIngredientRecipeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("RecipeVersionIngredientRecipeVersion")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("RecipeVersionIngredientFoodProductId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CaloriesPer100gSnapshot");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CarbohydratesPer100gSnapshot");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("FatPer100gSnapshot");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProteinPer100gSnapshot");

                            b1.HasKey("RecipeVersionIngredientRecipeId", "RecipeVersionIngredientRecipeVersion", "RecipeVersionIngredientFoodProductId");

                            b1.ToTable("RecipeVersionIngredients");

                            b1.WithOwner()
                                .HasForeignKey("RecipeVersionIngredientRecipeId", "RecipeVersionIngredientRecipeVersion", "RecipeVersionIngredientFoodProductId");
                        });

                    b.Navigation("NutritionPer100gSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.RecipeVersion", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
