// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionTracker.Infrastructure.Persistence;

#nullable disable

namespace NutritionTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    [Migration("20260722182615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("NutritionTracker.Domain.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Commands.ProcessedCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ProcessedCommands", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FiberPer100g")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("UserId");

                    b.ToTable("FoodProducts", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("Meals", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FoodProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MealId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecipeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodProductId");

                    b.HasIndex("MealId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("SourceMessageId");

                    b.ToTable("MealItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_MealItems_ExactlyOneSource", "(\"FoodProductId\" IS NOT NULL AND \"RecipeId\" IS NULL) OR (\"FoodProductId\" IS NULL AND \"RecipeId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NutritionTracker.Domain.Nutrition.NutritionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionTargets", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalPreparedWeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FoodProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("NutritionTracker.Domain.Chat.ChatMessage", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Commands.ProcessedCommand", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Foods.FoodProduct", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("NutritionTracker.Domain.Nutrition.NutritionValues", "NutritionPer100g", b1 =>
                        {
                            b1.Property<Guid>("FoodProductId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CaloriesPer100g");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CarbohydratesPer100g");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("FatPer100g");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProteinPer100g");

                            b1.HasKey("FoodProductId");

                            b1.ToTable("FoodProducts");

                            b1.WithOwner()
                                .HasForeignKey("FoodProductId");
                        });

                    b.Navigation("NutritionPer100g")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.Meal", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Meals.MealItem", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.FoodProduct", null)
                        .WithMany()
                        .HasForeignKey("FoodProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NutritionTracker.Domain.Meals.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Domain.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NutritionTracker.Domain.Chat.ChatMessage", null)
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("NutritionTracker.Domain.Nutrition.NutritionValues", "NutritionSnapshot", b1 =>
                        {
                            b1.Property<Guid>("MealItemId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CaloriesSnapshot");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CarbohydratesSnapshot");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("FatSnapshot");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProteinSnapshot");

                            b1.HasKey("MealItemId");

                            b1.ToTable("MealItems");

                            b1.WithOwner()
                                .HasForeignKey("MealItemId");
                        });

                    b.Navigation("NutritionSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Nutrition.NutritionTarget", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("NutritionTracker.Domain.Nutrition.NutritionValues", "NutritionValues", b1 =>
                        {
                            b1.Property<Guid>("NutritionTargetId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Calories")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("Calories");

                            b1.Property<decimal>("CarbohydrateGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CarbohydrateGrams");

                            b1.Property<decimal>("FatGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("FatGrams");

                            b1.Property<decimal>("ProteinGrams")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProteinGrams");

                            b1.HasKey("NutritionTargetId");

                            b1.ToTable("NutritionTargets");

                            b1.WithOwner()
                                .HasForeignKey("NutritionTargetId");
                        });

                    b.Navigation("NutritionValues")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.Recipe", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("NutritionTracker.Domain.Foods.FoodProduct", null)
                        .WithMany()
                        .HasForeignKey("FoodProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutritionTracker.Domain.Recipes.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionTracker.Domain.Recipes.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
